# Generated by Django 2.2.3 on 2019-07-13 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('akinwunmi_nathanielscrumy', '0002_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumygoals',
            name='owner',
            field=models.CharField(default=django.utils.timezone.now, max_length=340),
            preserve_default=False,
        ),
    ]
