# Generated by Django 2.2.3 on 2019-07-15 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akinwunmi_nathanielscrumy', '0003_scrumygoals_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumygoals',
            name='goal_id',
        ),
    ]
