# Generated by Django 2.2.3 on 2019-07-17 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('akinwunmi_nathanielscrumy', '0004_remove_scrumygoals_goal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumygoals',
            name='goal_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=340),
            preserve_default=False,
        ),
    ]
